# Generated by Django 2.2.6 on 2023-07-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_auto_20230703_1353'),
        ('jedzonko', '0002_plan'),
    ]

    operations = [
    ]
